### ISSUE TITLE
项目不是utf8编码

### ISSUE THREAD

**Issue by zhengxiaochuan** [Rano1/TopNews#1]
项目为什么不弄成utf8编码呢，在github上看代码中文都是乱码，导入到eclipse还是乱码，真心不爽啊，希望能够修改，谢谢！

**Comment by Rano1** [comment]
原本弄的时候，开发环境的默认编码是GBK所以没改，我改了后在上传次把

---

Carry on till tomorrow

------------------ 原始邮件 ------------------
发件人: "zhengxiaochuan";notifications@github.com;
发送时间: 2014年6月4日(星期三) 下午2:23
收件人: "Rano1/TopNews"TopNews@noreply.github.com; 

主题: [TopNews] 项目不是utf8编码 (#1)

项目为什么不弄成utf8编码呢，在github上看代码中文都是乱码，导入到eclipse还是乱码，真心不爽啊，希望能够修改，谢谢！

**Comment by zhengxiaochuan** [comment]
编码修改过啦，多谢啦 呵呵
